# NLog Configuration in TOML format for Autodesk Registry Cleaner
# This configuration provides comprehensive logging for all operations

[NLog]
throwConfigExceptions = true
internalLogLevel = "Warn"
internalLogFile = "logs/nlog-internal.log"

# Variables for log paths and formats
[NLog.variable]
logDirectory = "logs"
logFileBaseName = "autodesk-cleaner"
archiveDirectory = "logs/archive"

# Define targets for different log outputs
[[NLog.targets]]
name = "fileTarget"
type = "File"
fileName = "${var:logDirectory}/${var:logFileBaseName}-${date:format=yyyy-MM-dd}.log"
layout = "${longdate} [${level:uppercase=true}] ${logger} - ${message} ${exception:format=tostring}"
archiveFileName = "${var:archiveDirectory}/${var:logFileBaseName}-{#}.log"
archiveEvery = "Day"
archiveNumbering = "Date"
maxArchiveFiles = 30
concurrentWrites = true
keepFileOpen = false
encoding = "utf-8"

[[NLog.targets]]
name = "consoleTarget"
type = "ColoredConsole"
layout = "${time} [${level:uppercase=true:padding=-5}] ${message} ${exception:format=shorttype}"

# Operation-specific file target for detailed operation logs
[[NLog.targets]]
name = "operationTarget"
type = "File"
fileName = "${var:logDirectory}/operations/${var:logFileBaseName}-operation-${date:format=yyyy-MM-dd-HH-mm-ss}.log"
layout = "${longdate} [${level:uppercase=true}] ${logger} - ${message} ${exception:format=tostring}"
encoding = "utf-8"

# Error-specific file target
[[NLog.targets]]
name = "errorTarget"
type = "File"
fileName = "${var:logDirectory}/errors/${var:logFileBaseName}-errors-${date:format=yyyy-MM-dd}.log"
layout = "${longdate} [${level:uppercase=true}] ${logger} - ${message} ${exception:format=tostring}"
archiveFileName = "${var:archiveDirectory}/errors/${var:logFileBaseName}-errors-{#}.log"
archiveEvery = "Day"
archiveNumbering = "Date"
maxArchiveFiles = 90
encoding = "utf-8"

# Registry-specific logging target
[[NLog.targets]]
name = "registryTarget"
type = "File"
fileName = "${var:logDirectory}/registry/${var:logFileBaseName}-registry-${date:format=yyyy-MM-dd}.log"
layout = "${longdate} [${level:uppercase=true}] ${logger} - ${message} ${exception:format=tostring}"
archiveFileName = "${var:archiveDirectory}/registry/${var:logFileBaseName}-registry-{#}.log"
archiveEvery = "Day"
archiveNumbering = "Date"
maxArchiveFiles = 30
encoding = "utf-8"

# File system operations logging target
[[NLog.targets]]
name = "fileSystemTarget"
type = "File"
fileName = "${var:logDirectory}/filesystem/${var:logFileBaseName}-filesystem-${date:format=yyyy-MM-dd}.log"
layout = "${longdate} [${level:uppercase=true}] ${logger} - ${message} ${exception:format=tostring}"
archiveFileName = "${var:archiveDirectory}/filesystem/${var:logFileBaseName}-filesystem-{#}.log"
archiveEvery = "Day"
archiveNumbering = "Date"
maxArchiveFiles = 30
encoding = "utf-8"

# Define logging rules
[[NLog.rules]]
logger = "*"
minLevel = "Debug"
writeTo = "fileTarget"

[[NLog.rules]]
logger = "*"
minLevel = "Info"
writeTo = "consoleTarget"

[[NLog.rules]]
logger = "Autodesk_Cleaner.Core.*"
minLevel = "Debug"
writeTo = "operationTarget"

[[NLog.rules]]
logger = "*"
minLevel = "Error"
writeTo = "errorTarget"

[[NLog.rules]]
logger = "Autodesk_Cleaner.Core.AutodeskRegistryScanner"
minLevel = "Debug"
writeTo = "registryTarget"

[[NLog.rules]]
logger = "Autodesk_Cleaner.Core.AutodeskFileSystemCleaner"
minLevel = "Debug"
writeTo = "fileSystemTarget"
