# NLog Configuration in TOML format for Autodesk Registry Cleaner
# Simplified logging configuration using modern structured format

[NLog]
throwConfigExceptions = true
internalLogLevel = "Warn"
internalLogFile = "logs/nlog-internal.log"

# Variables for log paths and formats
[NLog.variable]
logDirectory = "logs"
logFileBaseName = "autodesk-cleaner"
archiveDirectory = "logs/archive"
modernLayout = "${longdate} [${level:uppercase=true}] ${logger} | ${message} | thread=${threadid} user=${environment-user} machine=${machinename} ${exception:format=tostring}"
jsonLayout = "${json-encode}"

# Main log file target (structured log format)
[[NLog.targets]]
name = "fileTarget"
type = "File"
fileName = "${var:logDirectory}/${var:logFileBaseName}-${date:format=yyyy-MM-dd}.log"
layout = "${var:modernLayout}"
archiveFileName = "${var:archiveDirectory}/${var:logFileBaseName}-{#}.log"
archiveEvery = "Day"
archiveNumbering = "Date"
maxArchiveFiles = 30
concurrentWrites = true
keepFileOpen = false
encoding = "utf-8"

# JSON structured log file target
[[NLog.targets]]
name = "jsonTarget"
type = "File"
fileName = "${var:logDirectory}/${var:logFileBaseName}-${date:format=yyyy-MM-dd}.json"
layout = "${var:jsonLayout}"
archiveFileName = "${var:archiveDirectory}/${var:logFileBaseName}-{#}.json"
archiveEvery = "Day"
archiveNumbering = "Date"
maxArchiveFiles = 30
concurrentWrites = true
keepFileOpen = false
encoding = "utf-8"

# TOML structured log file target
[[NLog.targets]]
name = "tomlTarget"
type = "TomlFile"
fileName = "${var:logDirectory}/${var:logFileBaseName}-${date:format=yyyy-MM-dd}.toml"
archiveFileName = "${var:archiveDirectory}/${var:logFileBaseName}-{#}.toml"
archiveEvery = "Day"
archiveNumbering = "Date"
maxArchiveFiles = 30
concurrentWrites = true
keepFileOpen = false
encoding = "utf-8"

# Console target for debugging
[[NLog.targets]]
name = "consoleTarget"
type = "ColoredConsole"
layout = "${time} [${level:uppercase=true:padding=-5}] ${message} ${exception:format=shorttype}"

# Logging rules
[[NLog.rules]]
logger = "*"
minLevel = "Info"
writeTo = "fileTarget"

[[NLog.rules]]
logger = "*"
minLevel = "Info"
writeTo = "jsonTarget"

[[NLog.rules]]
logger = "*"
minLevel = "Info"
writeTo = "tomlTarget"

[[NLog.rules]]
logger = "*"
minLevel = "Debug"
writeTo = "consoleTarget"
